development:
  adapter: postgresql
  encoding: unicode
  database: my_train_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: my_train_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: my_train_production
  pool: 5
